version: "3.1"

services:
  crawler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: crawler
    command: node crawler
    environment:
      - DB_URI=mongodb://mongodb:27017/multiverse
    depends_on:
      - mongodb
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    command: node api
    environment:
      - DB_URI=mongodb://mongodb:27017/multiverse
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017