version: "3.1"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: crawler
    command: node crawler
    environment:
      - DB_URI=mongodb://mongodb:27017/multiverse
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017