version: "3.1"

services:
  crawler:
    build:
      context: ./
      dockerfile: crawler.Dockerfile
    container_name: crawler
    command: node crawler
    environment:
      - DB_URL=mongodb://mongodb:27017/multiverse
    depends_on:
      - mongodb
  api:
    build:
      context: ./
      dockerfile: api.Dockerfile
    container_name: api
    command: node api
    environment:
      - DB_URL=mongodb://mongodb:27017/multiverse
      - PORT=3001
    depends_on:
      - mongodb
    ports:
      - 3001:3001
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
